//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetsuiteOnlineServicesOrders {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class GlobalSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalSettings defaultInstance = ((GlobalSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalSettings())));
        
        public static GlobalSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("607466")]
        public string nsAccount {
            get {
                return ((string)(this["nsAccount"]));
            }
            set {
                this["nsAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customersAcumByShippingDate {
            get {
                return ((string)(this["customersAcumByShippingDate"]));
            }
            set {
                this["customersAcumByShippingDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string nsCustomerTerms {
            get {
                return ((string)(this["nsCustomerTerms"]));
            }
            set {
                this["nsCustomerTerms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string culture {
            get {
                return ((string)(this["culture"]));
            }
            set {
                this["culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jmvargas@vistaflor.com")]
        public string nsUser {
            get {
                return ((string)(this["nsUser"]));
            }
            set {
                this["nsUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string nsCustomerForm {
            get {
                return ((string)(this["nsCustomerForm"]));
            }
            set {
                this["nsCustomerForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("119")]
        public string nsOrderForm {
            get {
                return ((string)(this["nsOrderForm"]));
            }
            set {
                this["nsOrderForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public string nsCustomerForm1 {
            get {
                return ((string)(this["nsCustomerForm1"]));
            }
            set {
                this["nsCustomerForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public string nsOrderForm1 {
            get {
                return ((string)(this["nsOrderForm1"]));
            }
            set {
                this["nsOrderForm1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string nsSalesRoleId {
            get {
                return ((string)(this["nsSalesRoleId"]));
            }
            set {
                this["nsSalesRoleId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("No")]
        public string AddLines {
            get {
                return ((string)(this["AddLines"]));
            }
            set {
                this["AddLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string nsRole {
            get {
                return ((string)(this["nsRole"]));
            }
            set {
                this["nsRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("459064")]
        public string nsSalesRep {
            get {
                return ((string)(this["nsSalesRep"]));
            }
            set {
                this["nsSalesRep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\\temp\\")]
        public string pathLog {
            get {
                return ((string)(this["pathLog"]));
            }
            set {
                this["pathLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fedex,UPS,Other,Transflora")]
        public string nsCourierType {
            get {
                return ((string)(this["nsCourierType"]));
            }
            set {
                this["nsCourierType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M4rt1n3z$")]
        public string nsPassword {
            get {
                return ((string)(this["nsPassword"]));
            }
            set {
                this["nsPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CST100WA,WA100AR,FIF100FL,GLO11FL,SOU100FL,AMA100WA")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DOCS,BLO,FIF,GLO,DDM,FLO,SOU,PAC,LST,FTD,ROS,FEX,AMA,BOU")]
        public string exSheet {
            get {
                return ((string)(this["exSheet"]));
            }
            set {
                this["exSheet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"CST100WA,LST100ME,DUD100TX,FIF100FL,FG100,SOU100FL,GLO100FL,PAC100CA,ST100COL,BLO100TX,LOR100NY,VSN100FL,VistaflorOnline,VOL100OH,ROS100NY,WWE100AR,WAL100AR,WAK100NJ,MIL100PA,RAI100PA,JWF100PR,INB100FL,FLO100FL,1800100PK,CHR200TX,CMK100TX,DBS100MO,KNO200AR,QUA200FL,MUL100BV,TKR100FL,XPA200FL,STO100PA,ECO100FL,DIL100AR,HOL100FL,MEI100MI,FLW100FL,1800100NY,FAL100MA,BRD100BV,WHO100TX,QUI100MA,WEI100PA,CST100UK,TEST100US,TEST1800NY,HOF100ON,WEG100NY,WIN100FL,1800300NY,CST100MX,FEX100FL,SIE100CA,KIN100NY,CYS100VT,AMA100WA,KEY100NH,BOU100CA,SUP100MN,FTD100IL,AHO100PA")]
        public string nsReseller {
            get {
                return ((string)(this["nsReseller"]));
            }
            set {
                this["nsReseller"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CST100WA,WA100AR,FIF100FL,GLO11FL,SOU100FL,GLO100FL,PAC100CA,ST100COL,BLO100TX,LO" +
            "R100NY,VSN100FL,VistaflorOnline,VOL100OH,ROS100NY,FEX100FL,AMA100WA,KEY100NH,BOU" +
            "100CA")]
        public string nsReseller1 {
            get {
                return ((string)(this["nsReseller1"]));
            }
            set {
                this["nsReseller1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IPD,IP,Domestic,FedexNextDay,DHL,BlueCargo,Other,Express Saver,Express")]
        public string nsShipType {
            get {
                return ((string)(this["nsShipType"]));
            }
            set {
                this["nsShipType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("468762")]
        public string nsParentCustomerTaxable {
            get {
                return ((string)(this["nsParentCustomerTaxable"]));
            }
            set {
                this["nsParentCustomerTaxable"] = value;
            }
        }
    }
}
